from casbin.enforcer import Enforcer
from casbin.util.rwlock import RWLockWrite, gen_synced_class

_SyncedEnforcer = gen_synced_class('_SyncedEnforcer', (Enforcer,),
    wl_functions=[
        Enforcer.clear_policy,
        Enforcer.load_policy,
        Enforcer.load_filtered_policy,
        Enforcer.add_named_policy,
        Enforcer.remove_policy,
        Enforcer.remove_filtered_policy,
        Enforcer.remove_named_policy,
        Enforcer.remove_filtered_named_policy,
        Enforcer.add_grouping_policy,
        Enforcer.add_named_grouping_policy,
        Enforcer.remove_grouping_policy,
        Enforcer.remove_filtered_grouping_policy,
        Enforcer.remove_named_grouping_policy,
        Enforcer.remove_filtered_named_grouping_policy,
        Enforcer.add_function,
        Enforcer.get_implicit_roles_for_user,
        Enforcer.get_implicit_permissions_for_user,
        Enforcer.get_implicit_users_for_permission,
    ], 
    rl_functions=[
        Enforcer.save_policy,
        Enforcer.build_role_links,
        Enforcer.enforce,
        Enforcer.get_all_subjects,
        Enforcer.get_all_named_subjects,
        Enforcer.get_all_objects,
        Enforcer.get_all_named_objects,
        Enforcer.get_all_actions,
        Enforcer.get_all_named_actions,
        Enforcer.get_all_roles,
        Enforcer.get_all_named_roles,
        Enforcer.get_policy,
        Enforcer.get_filtered_policy,
        Enforcer.get_named_policy,
        Enforcer.get_filtered_named_policy,
        Enforcer.get_grouping_policy,
        Enforcer.get_filtered_grouping_policy,
        Enforcer.get_named_grouping_policy,
        Enforcer.has_policy,
        Enforcer.has_named_policy,
        Enforcer.has_grouping_policy,
        Enforcer.has_named_grouping_policy,
        Enforcer.has_policy,
        Enforcer.has_policy,
        Enforcer.has_policy,
        Enforcer.has_policy,
        Enforcer.has_policy,
        Enforcer.has_policy,
        Enforcer.has_policy,
    ],
)

class SyncedEnforcer(_SyncedEnforcer, Enforcer):
    pass